-- MySQL Script generated by MySQL Workbench
-- Thu Jan 14 17:32:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TELEFONIA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TELEFONIA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TELEFONIA` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `TELEFONIA` ;

-- -----------------------------------------------------
-- Table `TELEFONIA`.`CALLS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TELEFONIA`.`CALLS` (
  `Num_Llamante` VARCHAR(13) NOT NULL,
  `Num_Llamado` VARCHAR(13) NOT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `Time` TIME NOT NULL,
  PRIMARY KEY (`Num_Llamante`, `Num_Llamado`),
  UNIQUE INDEX `Num_Llamante` (`Num_Llamante` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TELEFONIA`.`COMPANIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TELEFONIA`.`COMPANIES` (
  `ID_Comapania` INT NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `Anio_Fundacion` INT NOT NULL,
  PRIMARY KEY (`ID_Comapania`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TELEFONIA`.`PHONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TELEFONIA`.`PHONES` (
  `Numero` VARCHAR(11) NOT NULL,
  `NIF_Usuario` INT NOT NULL,
  `ID_Compania` INT NULL DEFAULT NULL,
  PRIMARY KEY (`Numero`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `TELEFONIA`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TELEFONIA`.`USERS` (
  `NIF` VARCHAR(9) NOT NULL,
  `Name` VARCHAR(20) NOT NULL,
  `LastName1` VARCHAR(20) NULL DEFAULT NULL,
  `LastName2` VARCHAR(20) NULL DEFAULT NULL,
  `Fec_Nacim` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`NIF`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
